age_sex_table <- readRDS("data/age_sex_table.RDS")
age_sex_table_wide <- readRDS("data/age_sex_table_wide.RDS")
big_census_data <- readRDS("data/big_census_data.RDS")
ca_education <- readRDS("data/ca_education.RDS")
county_diversity_percent <- readRDS("data/county_diversity_percent.RDS")
county_diversity_percent_plurality <- readRDS("data/county_diversity_percent_plurality.RDS")
county_diversity_percent_sorted <- readRDS("data/county_diversity_percent_sorted.RDS")
county_diversity_race <- readRDS("data/county_diversity_race.RDS")
county_map <- readRDS("data/county_map.RDS")
county_map_migration <- readRDS("data/county_map_migration.RDS")
county_migration <- readRDS("data/county_migration.RDS")
home_value_change <- readRDS("data/home_value_change.RDS")
income_table <- readRDS("data/income_table.RDS")
median_df <- readRDS("data/median_df.RDS")
median_income <- readRDS("data/median_income.RDS")
median_value <- readRDS("data/median_value.RDS")
median_value_1yr <- readRDS("data/median_value_1yr.RDS")
median_value_map <- readRDS("data/median_value_map.RDS")
pop20 <- readRDS("data/pop20.RDS")
poverty_df <- readRDS("data/poverty_df.RDS")
sa <- readRDS("data/sa_combined.RDS")
sa_groups <- readRDS("data/sa_groups.RDS")
sd_evictions <- readRDS("data/sd_evictions.RDS")
sd_tract_diversity <- readRDS("data/sd_tract_diversity.RDS")
sd_tract_diversity_plurality <- readRDS("data/sd_tract_diversity_plurality.RDS")
la_value <- readRDS("data/la_value.RDS")
state_ages <- readRDS("data/state_ages.RDS")
state_df <- readRDS("data/state_df.RDS")
somali1 <- readRDS("data/somali1.RDS")
somali5 <- readRDS("data/somali5.RDS")
tract_data <- readRDS("data/tract_data.RDS")
tract_df <- readRDS("data/tract_df.RDS")
vars <- readRDS("data/vars.RDS")
couples_table <- readRDS("data/couples_table.RDS")
couples_table_selected <- readRDS("data/couples_table_selected.RDS")
#https://data.census.gov/table/ACSSPP1Y2019.S0201?q=korean%20&hidePreview=false
#https://data.census.gov/table/ACSST5Y2016.S1701?q=below%20poverty%20level

#

